### ISSUE TITLE
Nightvision Module Flickering in Multiplayer

### ISSUE THREAD

**Issue by Whiskey-Sunshine** [budak7273/ArmorModules#1]
Current version: PowerSuit Modules 1.1.0
Satisfactory version: CL#131382

Issue: During the transition from night to day, the nightvision fading to normal light effect will constantly cycle. Only the host is experiencing this, other players connected to the host do not.

Details: The visual transition effect from bright to normal will start to cycle rapidly, starting at full brightness fading to normal, then abruptly going back to full brightness again, repeating endlessly. This will continue even when the power suit or the nightvision module are removed. Additionally, on rare occasions, the night vision effect will persist even during daylight hours causing excessively high brightness. The issues stop when the game is quit and reloaded. Edit: The day/night cycle length has not been changed from default or adjusted in any way.

Other information: Tested with all other mods removed and added one at a time to check for mod conflicts, the issues persisted even when it was only PowerSuit v0.3.1 and PowerSuit Modules v1.1.0

If you need any additional information, let me know what I need to pass on. I will do my best to respond as soon as possible.

**Comment by budak7273** [comment]
Thank you for the exceptionally thorough bug report. I really appreciate it.

Nog wrote the original blueprint code for the night vision module, so I have passed this issue along to him; I am very inexperienced with Unreal Engine blueprint logic. I'm guessing the exact same issues will exist for his night vision module as well.

I'll keep you updated here with more info, but since Nog is busy on another mod right now, it might take some time.

**Comment by budak7273** [comment]
Should be fixed as of the Update 4 version of the mod and Nog's rewrite of the module
