### ISSUE TITLE
[Suggestion] Toggle between JetPack and HoverPack

### ISSUE THREAD

**Issue by MikePrime21** [budak7273/ArmorModules#16]
I can't add both JetPack and HoverPack to the suit at the same time.  I'm guessing that's not a bug since the controls would get confusing.  But the modules don't show up in my inventory short cuts.  Its a pain to find the module from the many slots in my inventory (especially when its expanded with mods).  It would be nice if I could just equip both the JetPack and HoverPack and then just toggle between the two through some key binding or other way.

**Comment by budak7273** [comment]
This is possible with existing PowerSuit features, but I had not implemented it as a module, since I was not sure how to balance it in combination with other flight modules. The ability to do this can let you go absurdly fast in frictionless gravity flight mode.

If you install a mod that allows you to spawn items (ex. Nogs Cheats or Item Spawner) you should have access to a debug module called "Unlocked Flight Options Module." Installing it in your suit allows you to toggle using the Toggle Gravity Flight key you described. Could you please try it out and see if that is the behavior you are looking for? If so, I will plan to make it accessible normally it in the next release, and try to balance it some.

**Comment by MikePrime21** [comment]
I spent a day playing around with it.  When I equipped the integrated hover pack module with the Unlocked Flight Options Module I was able to do 90% of what I want.  The only issue I have is when using the toggle with the integrated hover pack, it behaves like the jet pack but it is even more powerful.  And when I have the Vertical/Horizontal thruster module equipped it becomes too powerful.  Otherwise its the exact functionality I'm looking for.  

Two things to note is that when un-equipping the flight options module, the state of the toggle remains.  Also when I rebind the key mappings, the don't change unless I restart the game.

**Comment by budak7273** [comment]
Thanks for the feedback. In a released version of the module, I would probably have to remove most if not all of the speed given by your jetpack(s) when in gravity mode.

The state of the toggle is an interesting problem for this module - I will probably have to look at other installed modules to determine what state to set you back to.

Interesting that the key mappings require a restart to change - does this happen to any of your other keybinds? We are using the SML keybind system, which hooks into the base game, so I would not expect this to be an issue.

I'll see what I can do for the next release. I'm not certain if this would best be offered as a flight module of its own (in place of your previous Flight Module, and allows you to toggle hover/not) or as an additional module (install this with whatever Flight Module you already have installed). What are your thoughts?

**Comment by budak7273** [comment]
A module that does this was added in Armor Modules 3.2.0 to the flight sub-mod, the Adaptive Flight Module. Thanks for your feedback!
