### ISSUE TITLE
WIP module expansion bug

### ISSUE THREAD

**Issue by vojtaBerry2** [budak7273/ArmorModules#19]
I want to report bug thet is if i grab something that change stats of power suit it delete items taht is in WIP expansion module
here is wat i mean: https://drive.google.com/file/d/1OqBABhOF5zhCd13CPGtAawrmizaHI0rn/view?usp=sharing

THANK FOR RESPONSE.

**Comment by budak7273** [comment]
Thanks for the report.

Please read the tooltip of the module, which is visible in the video you sent. I have copied it below for convenience.

```
WIP, this has not been released because it frequently causes item deletion. Use at your own risk

Uses the immense density of Nuclear Pasta to cram extra Modules into your Suit.

Suit slot count changes might only take into effect when you unequip and re-requip the suit. If you leave modules in the 'bonus space' and then lose the 'bonus space', the modules in those slots will be *deleted*.

Reduces Suit power capacity by 10%.
+3 Suit slots
Stacks with other modules of the same type.
```

Notably: "**this has not been released because it frequently causes item deletion.** Use at your own risk"

This module is only accessible via cheats because it still has a lot of bugs. The suit code has trouble handling changes in size, and neither Nog nor I have worked on it yet. As such, this module will stay cheats-only until that's fixed.

**Comment by vojtaBerry2** [comment]
ok that for response
