### ISSUE TITLE
[Issue building mod] TEST Has Foliage Idenifier in AssetRegistry.umap causes Alpakit build to fail

### ISSUE THREAD

**Issue by afewvowels** [budak7273/ArmorModules#35]
```
LogInit: Display: LogBlueprint: Warning: [AssetLog] D:\Creatives\SatisfactoryUnrealProject\Plugins\ArmorModules-master\Content\Debug\NeverPack\AssetRegistry.umap: [Compiler] Input pin  Identifier  specifying non-default value no longer exists on node  TEST Has Foliage Identifier . Please refresh node or reset pin to default value to remove pin.
```
Hello again! When I build the mod I get this error pointing to nodes in what appears to be some sort of debug test level. When I follow these instructions and refresh the nodes the errors resolve and the plugin builds, but oddly enough the mesh for the Equipment Bench buildable no longer works and turns into a single items of smart plating and also a single set of blade runners floating in mid-air. Otherwise everything works fine. Thanks!

**Comment by budak7273** [comment]
I purposefully exclude some assets from this repo because they're modified from Coffee Stain's models and redistributing them raw on GitHub seems unwise; the Equipment Workshop model is one of them. I forgot to mention that in [the last issue chain](https://github.com/budak7273/ArmorModules/issues/34#issuecomment-1837409183), sorry. Because of this, the Workshop model should have already been broken before you fixed the unrelated level node issues. Are you sure your edit to the level files was the cause of it breaking?

I have everything in the NeverPack folder set to not be shipped with the mod anyways, but your editor config probably doesn't have this setting, so it tried to pack them.

Unrelated, but, based on that error message, you've put the mod files your project's Plugins folder - you should put it in the Mods folder as described [here](https://docs.ficsit.app/satisfactory-modding/latest/Development/BeginnersGuide/ImportingAnotherMod.html) to avoid weird editor error states.

**Comment by budak7273** [comment]
I can send you the models privately for your personal builds, just let me know how you'd like me to get the files to you.

**Comment by budak7273** [comment]
Ah, I knew I had written [something about this before](https://github.com/budak7273/ArmorModules/blob/master/ASSET_NOTICE.md)

**Comment by afewvowels** [comment]
Thanks for that! I did just find the "Directories to never cook" and added the Debug/NeverPack directory to it and the mod builds just fine now. For anyone else tumbling down this rabbit hole I can save you a Google search and let you know for Unreal 5.2 it's under Project Settings >> Project >> Packaging >> Advanced >> Directories to never cook.
